name: Compose-Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ec2-54-175-200-184.compute-1.amazonaws.com
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ec2-user
        docker_compose_prefix: example_com
